#!/usr/bin/env bash


# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# install dependencies
sudo apt-get install -yqq build-essential cmake git mercurial python-dev python-pip \
	tmux vim zsh

# setup node
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
npm install -g npm eslint_d

# setup git
cp ./.gitconfig $HOME/
cp ./.gitignore $HOME/.gitignore_global

# retrieve base-16, prezto, tpm
git clone https://github.com/chriskempson/base16-shell.git $HOME/.config/base16-shell
git clone --recursive https://github.com/akrawchyk/prezto.git $HOME/.zprezto
git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm

# setup aliases
cp ./.aliases $HOME/

# setup functions
cp ./.functions $HOME/

# setup tmux
cp ./.tmux.conf $HOME/
$HOME/.tmux/plugins/tpm/bin/install_plugins

# setup vim
cp ./.vimrc $HOME/
mkdir $HOME/.vim
mkdir -p $HOME/.vim/tmp/undo
mkdir $HOME/.vim/backup
vim +PlugInstall +q

# setup prezto
# FIXME does not work in bash
# for rcfile in $( find $HOME/.zprezto/runcoms/ -name "z*" ); do
# 	ln -s $rcfile $HOME/.$( cut -d"/" -f6 $rcfile )
# done
chsh -s /bin/zsh


#logout
echo "Please logout.\n"
