[options]
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    filemanager = "defx"
    enable_guicolors = true
    statusline_separator = "arrow"
# statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    bootstrap_after = "customize#after"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "autocomplete"
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = "shell"
  default_position = "top"
  default_height = 30

[[layers]]
  name = "tmux"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "fzf"

[[layers]]
  name = "lsp"
  filetypes = [
    "ruby",
    "javascript",
    "typescript",
    "vue"
  ]
  [layers.override_cmd]
    ruby = ["solargraph", "stdio"]

[[layers]]
  name = "lang#json"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#xml"

[[layers]]
  name = "lang#vue"
  
[[layers]]
  name = "lang#ruby"

[[layers]]
  name = "test"
